### ISSUE TITLE
CSS inserted at top of Saxon-CE block of full inscription display

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usepweb_project#55]
There is some CSS that is inserted by the python code right before the Saxon CE inscription display happens. 
I'm using inscription 
You can see it here: view-source:https://usepigraphy.brown.edu/projects/usep/inscription/KY.Lou.SAM.L.1929.17.310/
lines 12-33

The part that wraps, for example is the text that follows the label "Condition"

It's coming from here: usepweb_project/usep_app/usep_templates/display_inscription.html
lines 6-27

it would be easier to manage if it were in a file with the rest of the CSS for the site. I think that's 
https://github.com/Brown-University-Library/usepweb_project/blob/master/usep_app/static/usep/css/style.css

then we can change things the way we do in IIP, where even though the CSS is in the django repository, at least it's a standalone file that I can edit and commit.

**Comment by emylonas** [comment]
Note that this is also https://github.com/Brown-University-Library/usep-data/issues/109 should be closed as well when fixed.

**Comment by birkin** [comment]
- implemented in commit 3ca2a9e28227f8889c72f15ef68bdab8b25fb933
- creates an inscription.css file at `usep_app/static/usep/css/inscription.css`
- at some point in the future, we could perhaps put that css file and the main css file in an appropriate usep-data directory so that you/others could update it and see results nearly live.

---
